In [7]:
from google.colab import files
uploaded = files.upload()

Saving Online Sales Data.csv to Online Sales Data.csv

In [10]:
import sqlite3
import pandas as pd
df = pd.read_csv("Online Sales Data.csv") # Preview data
print("Dataset Preview:")
display(df.head())

Dataset Preview:

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [12]:
df.columns

Index(['Transaction ID', 'Date', 'Product Category', 'Product Name',
       'Units Sold', 'Unit Price', 'Total Revenue', 'Region',
       'Payment Method'],
      dtype='object')

In [22]:
conn = sqlite3.connect('Online Sales.db')
df.to_sql('online_sales', conn, if_exists='replace', index=False)

240

In [24]:
query1 = '''
SELECT
STRFTIME('%Y-%m', "Date") AS YearMonth,
SUM("Total Revenue") AS MonthlyRevenue,
COUNT(DISTINCT "Transaction ID") AS OrderVolume
FROM online_sales
GROUP BY YearMonth
ORDER BY YearMonth
'''
monthly_stats = pd.read_sql_query(query1, conn)
print("Monthly Revenue and Order Volume:")
display(monthly_stats)

Monthly Revenue and Order Volume:

  YearMonth  MonthlyRevenue  OrderVolume
0   2024-01        14548.32           31
1   2024-02        10803.37           29
2   2024-03        12849.24           31
3   2024-04        12451.69           30
4   2024-05         8455.49           31
5   2024-06         7384.55           30
6   2024-07         6797.08           31
7   2024-08         7278.11           27

In [28]:
query2 = '''
SELECT
STRFTIME('%Y-%m', "Date") AS YearMonth,
SUM("Total Revenue") AS MonthlyRevenue,
COUNT(DISTINCT "Transaction ID") AS OrderVolume
FROM online_sales
GROUP BY YearMonth
ORDER BY MonthlyRevenue DESC
LIMIT 5
'''
top_revenue_months = pd.read_sql_query(query3, conn)
print("Top 5 Months by Revenue:")
display(top_revenue_months)

Top 5 Months by Revenue:

  YearMonth  MonthlyRevenue  OrderVolume
0   2024-01        14548.32           31
1   2024-03        12849.24           31
2   2024-04        12451.69           30
3   2024-02        10803.37           29
4   2024-05         8455.49           31

In [29]:
query3 = '''
SELECT
STRFTIME('%Y-%m', "Date") AS YearMonth,
SUM("Total Revenue") AS MonthlyRevenue,
COUNT(DISTINCT "Transaction ID") AS OrderVolume
FROM online_sales
GROUP BY YearMonth
ORDER BY OrderVolume DESC
LIMIT 5
'''
top_order_months = pd.read_sql_query(query4, conn)
print("Top 5 Months by Order Volume:")
display(top_order_months)

Top 5 Months by Order Volume:

  YearMonth  MonthlyRevenue  OrderVolume
0   2024-07         6797.08           31
1   2024-05         8455.49           31
2   2024-03        12849.24           31
3   2024-01        14548.32           31
4   2024-06         7384.55           30

In [36]:
from google.colab import files
import sqlite3
import pandas as pd

uploaded = files.upload()
df = pd.read_csv("Online Sales Data.csv")

# Convert Date to datetime, letting pandas infer format
df["Date"] = pd.to_datetime(df["Date"], errors='coerce')

# Drop rows where Date conversion failed
df = df.dropna(subset=["Date"])

# Format Date as YYYY-MM-DD for SQLite
df["Date"] = df["Date"].dt.strftime('%Y-%m-%d')

conn = sqlite3.connect(':memory:')
df.to_sql('online_sales', conn, index=False)

monthly_stats = pd.read_sql_query('''
SELECT
STRFTIME('%Y-%m', "Date") AS YearMonth,
SUM("Total Revenue") AS MonthlyRevenue,
COUNT(DISTINCT "Transaction ID") AS OrderVolume
FROM online_sales
GROUP BY YearMonth
ORDER BY YearMonth
''', conn)

display(monthly_stats)

top_revenue = monthly_stats.sort_values(by='MonthlyRevenue', ascending=False).head(5)
display(top_revenue)

top_orders = monthly_stats.sort_values(by='OrderVolume', ascending=False).head(5)
display(top_orders)

conn.close()

Saving Online Sales Data.csv to Online Sales Data (3).csv

  YearMonth  MonthlyRevenue  OrderVolume
0   2024-01        14548.32           31
1   2024-02        10803.37           29
2   2024-03        12849.24           31
3   2024-04        12451.69           30
4   2024-05         8455.49           31
5   2024-06         7384.55           30
6   2024-07         6797.08           31
7   2024-08         7278.11           27

  YearMonth  MonthlyRevenue  OrderVolume
0   2024-01        14548.32           31
2   2024-03        12849.24           31
3   2024-04        12451.69           30
1   2024-02        10803.37           29
4   2024-05         8455.49           31

  YearMonth  MonthlyRevenue  OrderVolume
0   2024-01        14548.32           31
2   2024-03        12849.24           31
6   2024-07         6797.08           31
4   2024-05         8455.49           31
5   2024-06         7384.55           30